package com.linayi.entity.settlement;

import java.math.BigDecimal;
import java.util.Date;

public class PromoterSettle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promoter_settle.id
     *
     * @mbg.generated Fri Mar 29 15:24:56 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promoter_settle.promoter_id
     *
     * @mbg.generated Fri Mar 29 15:24:56 CST 2019
     */
    private Integer promoterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promoter_settle.order_man_member_id
     *
     * @mbg.generated Fri Mar 29 15:24:56 CST 2019
     */
    private Integer orderManMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promoter_settle.orders_id
     *
     * @mbg.generated Fri Mar 29 15:24:56 CST 2019
     */
    private Long ordersId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promoter_settle.profit
     *
     * @mbg.generated Fri Mar 29 15:24:56 CST 2019
     */
    private BigDecimal profit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promoter_settle.profit_is_back
     *
     * @mbg.generated Fri Mar 29 15:24:56 CST 2019
     */
    private String profitIsBack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promoter_settle.back_time
     *
     * @mbg.generated Fri Mar 29 15:24:56 CST 2019
     */
    private Date backTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promoter_settle.create_time
     *
     * @mbg.generated Fri Mar 29 15:24:56 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promoter_settle.id
     *
     * @return the value of promoter_settle.id
     * @mbg.generated Fri Mar 29 15:24:56 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promoter_settle.id
     *
     * @param id the value for promoter_settle.id
     * @mbg.generated Fri Mar 29 15:24:56 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promoter_settle.promoter_id
     *
     * @return the value of promoter_settle.promoter_id
     * @mbg.generated Fri Mar 29 15:24:56 CST 2019
     */
    public Integer getPromoterId() {
        return promoterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promoter_settle.promoter_id
     *
     * @param promoterId the value for promoter_settle.promoter_id
     * @mbg.generated Fri Mar 29 15:24:56 CST 2019
     */
    public void setPromoterId(Integer promoterId) {
        this.promoterId = promoterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promoter_settle.order_man_member_id
     *
     * @return the value of promoter_settle.order_man_member_id
     * @mbg.generated Fri Mar 29 15:24:56 CST 2019
     */
    public Integer getOrderManMemberId() {
        return orderManMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promoter_settle.order_man_member_id
     *
     * @param orderManMemberId the value for promoter_settle.order_man_member_id
     * @mbg.generated Fri Mar 29 15:24:56 CST 2019
     */
    public void setOrderManMemberId(Integer orderManMemberId) {
        this.orderManMemberId = orderManMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promoter_settle.orders_id
     *
     * @return the value of promoter_settle.orders_id
     * @mbg.generated Fri Mar 29 15:24:56 CST 2019
     */
    public Long getOrdersId() {
        return ordersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promoter_settle.orders_id
     *
     * @param ordersId the value for promoter_settle.orders_id
     * @mbg.generated Fri Mar 29 15:24:56 CST 2019
     */
    public void setOrdersId(Long ordersId) {
        this.ordersId = ordersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promoter_settle.profit
     *
     * @return the value of promoter_settle.profit
     * @mbg.generated Fri Mar 29 15:24:56 CST 2019
     */
    public BigDecimal getProfit() {
        return profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promoter_settle.profit
     *
     * @param profit the value for promoter_settle.profit
     * @mbg.generated Fri Mar 29 15:24:56 CST 2019
     */
    public void setProfit(BigDecimal profit) {
        this.profit = profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promoter_settle.profit_is_back
     *
     * @return the value of promoter_settle.profit_is_back
     * @mbg.generated Fri Mar 29 15:24:56 CST 2019
     */
    public String getProfitIsBack() {
        return profitIsBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promoter_settle.profit_is_back
     *
     * @param profitIsBack the value for promoter_settle.profit_is_back
     * @mbg.generated Fri Mar 29 15:24:56 CST 2019
     */
    public void setProfitIsBack(String profitIsBack) {
        this.profitIsBack = profitIsBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promoter_settle.back_time
     *
     * @return the value of promoter_settle.back_time
     * @mbg.generated Fri Mar 29 15:24:56 CST 2019
     */
    public Date getBackTime() {
        return backTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promoter_settle.back_time
     *
     * @param backTime the value for promoter_settle.back_time
     * @mbg.generated Fri Mar 29 15:24:56 CST 2019
     */
    public void setBackTime(Date backTime) {
        this.backTime = backTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promoter_settle.create_time
     *
     * @return the value of promoter_settle.create_time
     * @mbg.generated Fri Mar 29 15:24:56 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promoter_settle.create_time
     *
     * @param createTime the value for promoter_settle.create_time
     * @mbg.generated Fri Mar 29 15:24:56 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}