package com.linayi.dao.settlement;

import com.linayi.entity.settlement.PromoterSettle;

public interface PromoterSettleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promoter_settle
     *
     * @mbg.generated Fri Mar 29 15:24:56 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promoter_settle
     *
     * @mbg.generated Fri Mar 29 15:24:56 CST 2019
     */
    int insert(PromoterSettle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promoter_settle
     *
     * @mbg.generated Fri Mar 29 15:24:56 CST 2019
     */
    int insertSelective(PromoterSettle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promoter_settle
     *
     * @mbg.generated Fri Mar 29 15:24:56 CST 2019
     */
    PromoterSettle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promoter_settle
     *
     * @mbg.generated Fri Mar 29 15:24:56 CST 2019
     */
    int updateByPrimaryKeySelective(PromoterSettle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promoter_settle
     *
     * @mbg.generated Fri Mar 29 15:24:56 CST 2019
     */
    int updateByPrimaryKey(PromoterSettle record);
}